marketing_metrics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: {{ env_var('DBT_HOST') }}
      user: {{ env_var('DBT_USER') }}
      password: {{ env_var('DBT_PASSWORD') }}
      port: {{ env_var('DBT_PORT', '5432') }}
      dbname: {{ env_var('DBT_DBNAME') }}
      schema: {{ env_var('DBT_SCHEMA', 'public') }}
      threads: 4
      keepalives_idle: 0